from admin.routes.index import *
from admin.routes.messages import *
from admin.routes.navlinks import *
from admin.routes.teams import *
from admin.routes.teamsimage import *
from admin.routes.portfoliocategory import *
from admin.routes.portfolio import *
from admin.routes.clients import *
from admin.routes.featuredservice import *
from admin.routes.service import *
from admin.routes.pricing import *
from admin.routes.pricingoption import *
from admin.routes.information import *
from admin.routes.testimonials import *
from admin.routes.features import *
from admin.routes.featureoptions import *
from admin.routes.blogs import *
from admin.routes.users import *
from admin.routes.test import *